export const THRESHOLDS = {
  EAR_BLINK: 0.20,
  EAR_WINK_CLOSED: 0.20,
  EAR_WINK_OPEN: 0.26,
  BLINK_MIN_DURATION_MS: 50,
  DOUBLE_BLINK_WINDOW_MS: 600,

  DWELL_TIME_MS: 1500,
  DWELL_FAST_MS: 800,
  DWELL_DECAY_RATE: 2,

  EXPR_HAPPY: 0.7,
  EXPR_SURPRISED: 0.6,
  EXPR_ANGRY: 0.5,
  EXPR_SAD: 0.5,
  EXPR_FEARFUL: 0.5,
  EXPR_DISGUSTED: 0.5,

  GAZE_SMOOTH_ALPHA: 0.25,
  HEAD_SMOOTH_ALPHA: 0.25,

  HEAD_TILT_THRESHOLD: 12,
  HEAD_NOD_VELOCITY: 15,
  HEAD_SHAKE_VELOCITY: 20,

  CALIB_HOLD_TIME_MS: 2000,
  CALIB_POINTS: 9,
  RECALIB_RESIZE_THRESHOLD: 100,
} as const

export const MODEL_PATH = '/models'
